Repository uwblueprint/jump-math, pull requests merged in 2023-08, with the labels that each got.

#496 feat: getStudentLeaderBoard
  backend/graphql/resolvers/testSessionResolvers.ts
  backend/graphql/types/testSessionType.ts
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
  frontend/src/APIClients/queries/TestSessionQueries.ts
Labels: requested changes

#497 feat: edit classroom button on classroom cards
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
Labels: ready to merge

#518 fix: Refactor response images to icons
  frontend/src/assets/icons.tsx
  frontend/src/assets/images.ts
  frontend/src/components/admin/question-creation/QuestionSidebar.tsx
  frontend/src/components/student/QuestionTypeImages.tsx
  frontend/src/constants/StudentAssessmentConstants.ts
Labels: ready for review

#531 fix: student experience design fixes
  frontend/src/components/student/NavButtons.tsx
  frontend/src/components/student/QuestionTypeImages.tsx
  frontend/src/components/student/SubmitButton.tsx
  frontend/src/components/student/questions/Question.tsx
  frontend/src/utils/StudentUtils.ts
Labels: ready for review

#478 feat: distribute assessment submission
  backend/graphql/types/testSessionType.ts
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
  backend/testUtils/testSession.ts
  backend/utilities/generalUtils.ts
  frontend/src/APIClients/types/TestSessionClientTypes.ts
  frontend/src/components/admin/assessment-status/EditStatusButtons/ArchiveButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/DeleteButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/EditButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/PublishButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/DuplicateModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/UnarchiveModal.tsx
  frontend/src/components/admin/user-management/RemoveUserModal.tsx
  frontend/src/components/auth/ResendEmail.tsx
  frontend/src/components/common/info/useToast.tsx
  frontend/src/components/pages/teacher/DistributeAssessmentPage.tsx
  frontend/src/components/student/SubmitButton.tsx
  frontend/src/components/teacher/session-creation/DistributeAssessmentButton.tsx
  frontend/src/components/teacher/session-creation/DistributeAssessmentModal.tsx
  frontend/src/components/teacher/student-management/AddStudentModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddClassroomModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddOrEditClassroomModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemPopover.tsx
  frontend/src/utils/TestSessionUtils.ts
Labels: ready for review

#491 (1) add classroom section component for teacher dashboard
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/resolvers/scalarResolvers.ts
  backend/graphql/types/classType.ts
  backend/graphql/types/scalarType.ts
  backend/models/class.model.ts
  backend/services/implementations/classService.ts
  backend/services/interfaces/classService.ts
  backend/types/index.ts
  backend/utilities/generalUtils.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/components/common/info/messages/EmptyClassroomsGoToPage.tsx
  frontend/src/components/common/info/messages/EmptyClassroomsMessage.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/teacher/dashboard/ClassroomsSection.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseClass.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomCard.tsx
  frontend/src/components/teacher/student-management/classroom-summary/useClassDataQuery.ts
Labels: ready for review

#492 (2) add assessment section component for teacher dashboard
  backend/graphql/resolvers/testSessionResolvers.ts
  backend/graphql/types/testSessionType.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
  frontend/src/APIClients/queries/TestSessionQueries.ts
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/components/pages/teacher/DisplayAssessmentsPage.tsx
  frontend/src/components/teacher/dashboard/AssessmentsSection.tsx
  frontend/src/components/teacher/view-sessions/useAssessmentDataQuery.ts
Labels: ready to merge

#493 feat: add teacher dashboard
  frontend/src/components/common/info/messages/EmptyClassroomsGoToPage.tsx
  frontend/src/components/common/popover/Popover.tsx
  frontend/src/components/common/popover/SimplePopover.tsx
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/pages/teacher/TeacherDashboardPage.tsx
  frontend/src/components/teacher/student-management/view-students/AddClassroomOrStudentPopover.tsx
Labels: ready to merge

#545 chore: disable version updates by dependabot
  .github/dependabot.yml
Labels: ready to merge

#533 feat: filter out completed students from name selection
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/resolvers/testSessionResolvers.ts
  backend/graphql/types/classType.ts
  backend/services/implementations/__tests__/classService.test.ts
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/classService.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/classService.ts
  backend/testUtils/classAssertions.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/components/auth/student-login/NameSelection.tsx
Labels: ready to merge

#532 fix: bugs surrounding edit-classroom modal
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddOrEditClassroomModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomCard.tsx
  frontend/src/utils/GeneralUtils.ts
Labels: ready for review

#548 feat: create generic component for multi options
  frontend/src/components/admin/question-creation/question-elements/FractionElement.tsx
  frontend/src/components/admin/question-creation/question-elements/MultiOptionElement.tsx
  frontend/src/components/admin/question-creation/question-elements/modals/fraction/FractionModal.tsx
  frontend/src/components/common/question-elements/fraction/FractionFieldInput.tsx
  frontend/src/components/common/question-elements/fraction/FractionInput.tsx
  frontend/src/components/common/question-elements/multi-option/MultiOptionInput.tsx
  frontend/src/components/common/question-elements/multi-option/MultiSelectInput.tsx
  frontend/src/components/common/question-elements/multi-option/MultipleChoiceInput.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/components/student/questions/question-elements/Fraction.tsx
  frontend/src/components/student/questions/question-elements/MultiSelect.tsx
  frontend/src/components/student/questions/question-elements/MultipleChoice.tsx
Labels: ready to merge

#544 feat: query for school by teacher id
  backend/graphql/resolvers/schoolResolvers.ts
  backend/graphql/types/schoolType.ts
  backend/services/implementations/__tests__/schoolService.test.ts
  backend/services/implementations/schoolService.ts
  backend/services/interfaces/schoolService.ts
  frontend/src/APIClients/queries/SchoolQueries.ts
  frontend/src/components/admin/user-management/admin/AdminUserTable.tsx
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/teacher-signup/index.tsx
  frontend/src/components/pages/teacher/DistributeAssessmentPage.tsx
  frontend/src/types/AuthTypes.ts
Labels: ready to merge

#547 feat: archiving + archived classrooms
  frontend/src/APIClients/mutations/ClassMutations.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/APIClients/types/ClassClientTypes.ts
  frontend/src/App.tsx
  frontend/src/checkFeatureFlag.ts
  frontend/src/components/common/modal/Modal.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/teacher/dashboard/ClassroomsSection.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseClass.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomCard.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
  frontend/src/components/teacher/student-management/classroom-summary/DeleteClassroomModal.tsx
  frontend/src/types/ClassroomTypes.tsx
Labels: ready to merge

#546 fix: test session limiting and sorting on dashboard
  backend/graphql/types/scalarType.ts
  backend/graphql/types/testSessionType.ts
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
  backend/testUtils/testSession.ts
  backend/utilities/testSessionUtils.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/APIClients/queries/TestSessionQueries.ts
  frontend/src/APIClients/types/TestSessionClientTypes.ts
  frontend/src/components/pages/teacher/DisplayAssessmentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
  frontend/src/components/teacher/dashboard/AssessmentsSection.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseClass.tsx
  frontend/src/components/teacher/student-management/classroom-summary/useClassDataQuery.ts
  frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemPopover.tsx
  frontend/src/components/teacher/view-sessions/useAssessmentDataQuery.ts
  frontend/src/types/TestSessionTypes.ts
  frontend/src/utils/TestSessionUtils.ts
Labels: ready to merge

#551 fix: only delete upcoming test sessions
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
  frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemPopover.tsx
Labels: ready for review

#556 fix: remove archived classes from test distribution
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  frontend/src/components/teacher/session-creation/steps/ChooseClass.tsx
Labels: ready to merge

#552 fix: remove unused code
  backend/graphql/index.ts
  backend/graphql/resolvers/entityResolvers.ts
  backend/graphql/resolvers/schoolResolvers.ts
  backend/graphql/resolvers/simpleEntityResolvers.ts
  backend/graphql/resolvers/userResolvers.ts
  backend/graphql/types/entityType.ts
  backend/graphql/types/schoolType.ts
  backend/graphql/types/simpleEntityType.ts
  backend/graphql/types/userType.ts
  backend/models/entity.model.ts
  backend/models/simpleEntity.model.ts
  backend/services/implementations/__tests__/schoolService.test.ts
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/__tests__/userService.test.ts
  backend/services/implementations/entityService.ts
  backend/services/implementations/schoolService.ts
  backend/services/implementations/simpleEntityService.ts
  backend/services/implementations/testSessionService.ts
  backend/services/implementations/userService.ts
  backend/services/interfaces/IEntityService.ts
  backend/services/interfaces/schoolService.ts
  backend/services/interfaces/simpleEntityService.ts
  backend/services/interfaces/testSessionService.ts
  backend/services/interfaces/userService.ts
  backend/testUtils/school.ts
  e2e-tests/cat.png
  e2e-tests/conftest.py
  e2e-tests/dog.jpg
  e2e-tests/test_auth_gql.py
  e2e-tests/test_entity_gql.py
  e2e-tests/test_simple_entity_gql.py
  e2e-tests/test_user_gql.py
  frontend/src/APIClients/mutations/AuthMutations.ts
Labels: ready to merge

#550 feat: student deletion
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/types/classType.ts
  backend/services/implementations/classService.ts
  frontend/src/APIClients/mutations/ClassMutations.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/APIClients/types/ClassClientTypes.ts
  frontend/src/components/common/modal/Modal.tsx
  frontend/src/components/common/table/SearchableTablePage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomStudentsPage.tsx
  frontend/src/components/teacher/student-management/classroom-summary/DeleteClassroomModal.tsx
  frontend/src/components/teacher/student-management/view-students/EditStudentPopover.tsx
  frontend/src/components/teacher/student-management/view-students/StudentListPopover.tsx
  frontend/src/components/teacher/student-management/view-students/StudentsTable.tsx
Labels: ready for review

#554 fix: remove the ability to edit archived classrooms
  backend/services/implementations/classService.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/APIClients/types/ClassClientTypes.ts
  frontend/src/components/common/info/messages/EmptyClassSessionsMessage.tsx
  frontend/src/components/common/info/messages/EmptyClassStudentsMessage.tsx
  frontend/src/components/common/table/SearchableTablePage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomStudentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomCard.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
Labels: ready to merge

#558 feat: edit student
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/types/classType.ts
  frontend/src/APIClients/mutations/ClassMutations.ts
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/teacher/student-management/AddOrEditStudentModal.tsx
  frontend/src/components/teacher/student-management/view-students/StudentListPopover.tsx
  frontend/src/types/ClassroomTypes.tsx
Labels: ready to merge

#557 [hold] feat: enable archive classroom feature
  frontend/src/checkFeatureFlag.ts
Labels: ready to merge

#559 fix: minor auth fixes
  backend/graphql/resolvers/authResolvers.ts
  backend/graphql/resolvers/schoolResolvers.ts
  backend/services/implementations/schoolService.ts
  backend/services/interfaces/schoolService.ts
  backend/testUtils/school.ts
  frontend/src/APIClients/queries/SchoolQueries.ts
  frontend/src/APIClients/types/SchoolClientTypes.ts
  frontend/src/components/auth/password/PasswordForm.tsx
  frontend/src/components/auth/reset-password/ForgotPassword.tsx
  frontend/src/components/auth/teacher-signup/NavigationButtons.tsx
  frontend/src/components/auth/teacher-signup/steps/TeacherSignUpOne.tsx
  frontend/src/components/auth/teacher-signup/steps/TeacherSignupFour.tsx
Labels: ready to merge
