Repository uwblueprint/jump-math, pull requests merged in 2023-09, with the labels that each got.

#562 fix: Remove test session field from class (1)
  backend/graphql/resolvers/testSessionResolvers.ts
  backend/models/class.model.ts
  backend/services/implementations/__tests__/classService.test.ts
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/classService.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/classService.ts
  backend/testUtils/class.ts
  backend/testUtils/classAssertions.ts
Labels: ready for review

#563 fix: remove class field from teacher (2)
  backend/graphql/resolvers/classResolvers.ts
  backend/models/class.model.ts
  backend/models/user.model.ts
  backend/services/implementations/userService.ts
  backend/types/index.ts
Labels: ready for review

#561 feat: delete test sessions on class deletion (3)
  backend/models/class.model.ts
  backend/models/user.model.ts
  backend/services/implementations/__tests__/classService.test.ts
  backend/services/implementations/__tests__/userService.test.ts
  backend/services/implementations/testService.ts
Labels: ready for review

#564 fix: handle test session references on class archive (4)
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/types/classType.ts
  backend/services/implementations/__tests__/classService.test.ts
  backend/services/implementations/classService.ts
  backend/services/interfaces/classService.ts
  frontend/src/APIClients/mutations/ClassMutations.ts
  frontend/src/components/common/modal/Modal.tsx
  frontend/src/components/common/modal/ModalText.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
Labels: ready to merge

#560 fix: hide data visualization behind a ff
  frontend/src/checkFeatureFlag.ts
  frontend/src/components/admin/view-assessments/AssessmentsTable.tsx
  frontend/src/components/pages/teacher/DisplayAssessmentResultsPage/index.tsx
Labels: ready to merge

#571 fix: expired refresh token issues
  backend/services/implementations/authService.ts
  frontend/src/index.tsx
Labels: ready to merge

#495 fix: add contextually-appropriate titles to all pages
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/PrivateRoute.tsx
  frontend/src/components/auth/RedirectTo.tsx
  frontend/src/components/auth/usePageTitle.ts
  frontend/src/components/pages/Landing.tsx
  frontend/src/components/pages/NotFound.tsx
  frontend/src/components/pages/RedirectTo.tsx
  frontend/src/components/pages/admin/AdminRouting.tsx
  frontend/src/components/pages/admin/AssessmentEditorPage.tsx
  frontend/src/components/pages/student/AssessmentSummaryPage.tsx
  frontend/src/components/pages/student/StudentLoginPage.tsx
  frontend/src/components/pages/student/StudentRouting.tsx
  frontend/src/components/pages/student/WriteAssessmentPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/pages/teacher/TeacherRouting.tsx
Labels: ready to merge

#568 (1) feat: edit test sessions
  backend/graphql/resolvers/testSessionResolvers.ts
  backend/graphql/types/testSessionType.ts
  frontend/src/APIClients/mutations/TestSessionMutations.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/APIClients/queries/TestSessionQueries.ts
  frontend/src/APIClients/types/ClassClientTypes.ts
  frontend/src/APIClients/types/TestSessionClientTypes.ts
  frontend/src/components/common/DatePicker.tsx
  frontend/src/components/common/info/messages/EmptyClassSessionsMessage.tsx
  frontend/src/components/common/info/messages/EmptySessionsMessage.tsx
  frontend/src/components/common/table/Table.tsx
  frontend/src/components/pages/teacher/DisplayAssessmentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/pages/teacher/DistributeAssessmentPage.tsx
  frontend/src/components/teacher/dashboard/AssessmentsSection.tsx
  frontend/src/components/teacher/session-creation/AssessmentsTable.tsx
  frontend/src/components/teacher/session-creation/DistributeAssessmentButton.tsx
  frontend/src/components/teacher/session-creation/ReviewItem.tsx
  frontend/src/components/teacher/session-creation/steps/AddInformation.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseAssessment.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseClass.tsx
  frontend/src/components/teacher/session-creation/steps/Review.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemPopover.tsx
  frontend/src/components/teacher/view-sessions/useAssessmentDataQuery.ts
Labels: ready to merge

#572 feat: delete student results on student deletion
  backend/services/implementations/__tests__/classService.test.ts
  backend/services/implementations/classService.ts
Labels: ready to merge

#573 fix: fix question number padding
  frontend/src/components/student/QuestionNumber.tsx
Labels: ready to merge

#570 (2) feat: add backend validation for edit test session
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
  backend/testUtils/testSession.ts
Labels: ready for review

#569 (1) fix: clean up modal logic surrounding admin assessments
  frontend/src/components/admin/assessment-creation/AssessmentEditorHeader.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/ArchiveButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/DeleteButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/DuplicateButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/PublishButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusButtons/UnarchiveButton.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/ArchiveAssessmentModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/ArchiveModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/DeleteAssessmentModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/DeleteModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/DuplicateAssessmentModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/DuplicateModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/PublishAssessmentModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/PublishModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/UnarchiveAssessmentModal.tsx
  frontend/src/components/admin/assessment-status/EditStatusModals/UnarchiveModal.tsx
  frontend/src/components/common/form/ActionButton.tsx
  frontend/src/components/common/modal/Modal.tsx
  frontend/src/components/common/popover/PopoverButton.tsx
  frontend/src/components/pages/admin/AssessmentEditorPage.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemPopover.tsx
  frontend/src/utils/GeneralUtils.ts
Labels: ready to merge

#574 fix: fix test session list item UI
  frontend/src/components/common/navigation/RouterTabs.tsx
  frontend/src/components/pages/teacher/DisplayAssessmentResultsPage/DisplayAssessmentResultsByStudentPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemBody.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemClassNameTag.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemStatistics.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemStatusTag.tsx
Labels: ready to merge

#575 feat: delete images on test edit
  backend/services/implementations/__tests__/testService.test.ts
  backend/services/implementations/imageUploadService.ts
  backend/services/implementations/testService.ts
  backend/testUtils/tests.ts
Labels: ready for review

#576 (2) fix: clean up modal logic surrounding teacher classrooms
  backend/services/implementations/__tests__/classService.test.ts
  backend/services/implementations/classService.ts
  frontend/src/components/common/form/ControlledDatePicker.tsx
  frontend/src/components/common/form/ControlledSelect.tsx
  frontend/src/components/common/form/DatePicker.tsx
  frontend/src/components/common/form/InlineFormError.tsx
  frontend/src/components/common/info/toasts/ErrorToast.tsx
  frontend/src/components/common/modal/Modal.tsx
  frontend/src/components/common/modal/ModalText.tsx
  frontend/src/components/common/modal/useModalFormHandler.tsx
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/teacher/session-creation/steps/AddInformation.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddOrEditClassroomModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ArchiveClassroomModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
  frontend/src/components/teacher/student-management/classroom-summary/DeleteClassroomModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/SelectFormInputClassroom.tsx
  frontend/src/themes/colors.ts
  frontend/src/themes/components/input.ts
  frontend/src/types/ClassroomTypes.tsx
Labels: ready to merge

#565 (1) feat: preview question
  frontend/src/components/admin/question-creation/QuestionEditor.tsx
  frontend/src/components/admin/question-creation/QuestionPreview.tsx
  frontend/src/components/admin/question-creation/QuestionSidebar.tsx
  frontend/src/components/pages/student/WriteAssessmentPage.tsx
  frontend/src/components/student/AssessmentExperience.tsx
  frontend/src/components/student/NavButtons.tsx
  frontend/src/components/student/QuestionNumbers.tsx
  frontend/src/components/student/StudentDashboardHeader.tsx
  frontend/src/components/student/SubmitButton.tsx
  frontend/src/components/student/questions/Question.tsx
  frontend/src/components/student/questions/QuestionTitle.tsx
  frontend/src/components/student/questions/question-elements/MultiSelect.tsx
  frontend/src/components/student/questions/question-elements/MultipleChoice.tsx
  frontend/src/components/student/questions/question-elements/useAnswerState.ts
  frontend/src/contexts/AssessmentExperienceContext.ts
  frontend/src/contexts/QuestionEditorContext.ts
  frontend/src/contexts/WriteAssessmentContext.ts
  frontend/src/utils/StudentUtils.ts
Labels: ready to merge

#566 (2) feat: preview assessment
  frontend/src/assets/icons.tsx
  frontend/src/components/admin/assessment-creation/AssessmentEditorHeader.tsx
  frontend/src/components/admin/assessment-creation/AssessmentPreview.tsx
  frontend/src/components/pages/admin/AssessmentEditorPage.tsx
  frontend/src/contexts/AssessmentContext.ts
Labels: ready to merge

#577 (3) fix: clean up more modal logic
  frontend/src/components/common/form/ActionButton.tsx
  frontend/src/components/common/modal/Modal.tsx
  frontend/src/components/common/popover/PopoverButton.tsx
  frontend/src/components/pages/student/AssessmentSummaryPage.tsx
  frontend/src/components/student/SubmitButton.tsx
  frontend/src/components/teacher/session-creation/DistributeAssessmentButton.tsx
  frontend/src/components/teacher/session-creation/DistributeAssessmentModal.tsx
  frontend/src/components/teacher/student-management/AddOrEditStudentModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddOrEditClassroomModal.tsx
  frontend/src/components/teacher/student-management/view-students/StudentListPopover.tsx
Labels: ready for review

#579 (5) fix: final modal fixes
  frontend/src/components/admin/user-management/admin/AddAdminModal.tsx
  frontend/src/components/admin/user-management/admin/AddAdminModal/ConfirmationModal.tsx
  frontend/src/components/admin/user-management/admin/AddAdminModal/FormModal.tsx
  frontend/src/components/admin/user-management/admin/AddAdminModal/index.tsx
  frontend/src/components/common/modal/Modal.tsx
Labels: ready to merge

#582 fix: stale data issues in assessment editor
  frontend/src/components/admin/question-creation/question-elements/modals/fraction/FractionModal.tsx
  frontend/src/components/admin/question-creation/question-elements/modals/multi-option/MultiOptionModal.tsx
  frontend/src/components/admin/question-creation/question-elements/modals/short-answer/ShortAnswerModal.tsx
Labels: ready to merge

#583 fix: admin nav issues
  frontend/src/components/admin/user-management/UsersPageHeader.tsx
  frontend/src/components/admin/user-management/admin/AddAdminModal/ConfirmationModal.tsx
  frontend/src/components/pages/admin/AdminRouting.tsx
  frontend/src/components/pages/admin/UsersPage.tsx
  frontend/src/constants/Routes.ts
Labels: ready to merge

#589 fix: popover styling
  frontend/src/components/admin/user-management/RemoveUserModal.tsx
  frontend/src/components/admin/user-management/RemoveUserPopover.tsx
  frontend/src/components/common/popover/Popover.tsx
  frontend/src/components/common/popover/PopoverButton.tsx
  frontend/src/themes/components/button.ts
  frontend/src/themes/components/popover.ts
  frontend/src/themes/index.ts
Labels: question

#590 fix: loading state for buttons
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/Logout.tsx
  frontend/src/components/auth/password/PasswordForm.tsx
  frontend/src/components/auth/reset-password/ForgotPassword.tsx
  frontend/src/components/auth/teacher-signup/NavigationButtons.tsx
  frontend/src/components/common/form/ActionButton.tsx
  frontend/src/components/common/modal/ModalFooterButtons.tsx
  frontend/src/themes/components/button.ts
Labels: ready for review

#584 fix: keep dashboard add-class modal on same page
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/pages/teacher/TeacherDashboardPage.tsx
  frontend/src/constants/ClassroomConstants.ts
Labels: ready to merge

#581 fix: popovers should auto-close from class cards
  frontend/src/components/admin/assessment-creation/AssessmentEditorHeader.tsx
  frontend/src/components/admin/assessment-status/EditStatusPopover.tsx
  frontend/src/components/common/popover/Popover.tsx
  frontend/src/components/common/popover/PopoverButton.tsx
  frontend/src/components/common/popover/PopoverContext.ts
  frontend/src/components/common/popover/SimplePopover.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
  frontend/src/components/teacher/student-management/view-students/StudentListPopover.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemPopover.tsx
Labels: ready to merge

#587 feat: update back button in assessment and question editor
  frontend/src/components/admin/assessment-creation/AssessmentEditorHeader.tsx
  frontend/src/components/admin/question-creation/QuestionSidebar.tsx
  frontend/src/components/common/navigation/BackButton.tsx
  frontend/src/components/pages/teacher/DisplayAssessmentResultsPage/index.tsx
Labels: ready to merge

#586 feat: add view all states to teacher dashboard
  frontend/src/components/pages/teacher/TeacherDashboardPage.tsx
  frontend/src/components/teacher/dashboard/AssessmentsSection.tsx
  frontend/src/components/teacher/dashboard/ClassroomsSection.tsx
  frontend/src/components/teacher/dashboard/ViewAllLink.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomCard.tsx
Labels: ready to merge

#588 feat: add archived class indicator
  frontend/src/assets/icons.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
Labels: ready to merge

#580 fix: change teacher dashboard tab design to standard tabs
  frontend/src/APIClients/types/TestSessionClientTypes.ts
  frontend/src/components/pages/teacher/DisplayAssessmentsPage.tsx
  frontend/src/components/pages/teacher/DistributeAssessmentPage.tsx
  frontend/src/components/teacher/dashboard/AssessmentsSection.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItemPopover.tsx
  frontend/src/components/teacher/view-sessions/TestSessionTabs.tsx
  frontend/src/components/teacher/view-sessions/useAssessmentDataQuery.ts
Labels: ready to merge

#593 (1) feat: make generic component for error and load state
  frontend/src/components/common/QueryStateHandler.tsx
  frontend/src/components/pages/admin/DisplayAssessmentsPage.tsx
  frontend/src/components/pages/admin/UsersPage.tsx
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomStudentsPage.tsx
  frontend/src/components/pages/teacher/TeacherDashboardPage.tsx
  frontend/src/components/teacher/dashboard/AssessmentsSection.tsx
  frontend/src/components/teacher/dashboard/ClassroomsSection.tsx
  frontend/src/components/teacher/session-creation/DistributeAssessmentWrapper.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseAssessment.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseClass.tsx
  frontend/src/components/teacher/view-sessions/useAssessmentDataQuery.ts
Labels: ready to merge

#585 feat: better assessment editor loading state
  frontend/src/APIClients/mutations/TestMutations.ts
  frontend/src/components/admin/assessment-creation/AssessmentEditorHeader.tsx
  frontend/src/components/common/form/ActionButton.tsx
  frontend/src/components/common/modal/useActionFormHandler.tsx
  frontend/src/components/common/navigation/useReloadPrompt.ts
  frontend/src/components/pages/admin/AssessmentEditorPage.tsx
  frontend/src/components/teacher/student-management/AddOrEditStudentModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddOrEditClassroomModal.tsx
Labels: ready to merge

#596 Add empty state for individual classrooms page tabs
  frontend/src/components/common/info/messages/EmptyArchivedClassroomsMessage.tsx
  frontend/src/components/common/info/messages/EmptyClassroomsMessage.tsx
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
Labels: question, ready to merge
