Repository uwblueprint/jump-math, pull requests merged in 2023-07, with the labels that each got.

#440 feat: get mark distribution for test session
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
Labels: ready to merge

#444 feat: get performance by question for test session
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
Labels: ready to merge

#441 feat: graph visualization component
  frontend/package.json
  frontend/src/components/data-visualization/BarGraph.tsx
  frontend/src/components/data-visualization/ChartSection.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/themes/components/tabs.ts
  frontend/yarn.lock
Labels: ready to merge

#442 feat: add active assessment field to class card
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/types/classType.ts
  backend/services/interfaces/classService.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/APIClients/types/ClassClientTypes.ts
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/teacher/student-management/classrooms/ClassroomCard.tsx
  frontend/src/types/ClassroomTypes.tsx
Labels: ready to merge

#369 fix: Show correct login error
  frontend/src/APIClients/AuthAPIClient.ts
  frontend/src/components/auth/Login.tsx
  frontend/src/components/auth/teacher-signup/index.tsx
  frontend/src/components/auth/teacher-signup/steps/TeacherSignUpOne.tsx
  frontend/src/components/auth/teacher-signup/steps/TeacherSignupFour.tsx
  frontend/src/components/auth/teacher-signup/steps/TeacherSignupThree.tsx
  frontend/src/types/TeacherSignupTypes.tsx
Labels: requested changes

#460 fix: classroom card spacing
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
Labels: ready for review

#276 backend: Archive Classroom
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/types/classType.ts
  backend/models/class.model.ts
  backend/services/implementations/__tests__/classService.test.ts
  backend/services/implementations/classService.ts
  backend/services/interfaces/classService.ts
  backend/testUtils/classAssertions.ts
Labels: ready to merge

#424 (3) feat: view students in class
  frontend/src/APIClients/types/ClassClientTypes.ts
  frontend/src/assets/illustrations/display-students.svg
  frontend/src/assets/illustrations/mobile-redirect.svg
  frontend/src/components/admin/view-assessments/AssessmentsTab.tsx
  frontend/src/components/auth/RedirectTo.tsx
  frontend/src/components/common/info/messages/EmptyStudentsMessage.tsx
  frontend/src/components/common/info/messages/MobileRedirectMessage.tsx
  frontend/src/components/common/navigation/RouterTabs.tsx
  frontend/src/components/common/table/SearchableTablePage.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/components/pages/admin/DisplayAssessmentsPage.tsx
  frontend/src/components/pages/teacher/ClassroomsPage.tsx
  frontend/src/components/pages/teacher/DisplayAssessmentResultsPage/index.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomStudentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddClassroomModal.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomCard.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
  frontend/src/components/teacher/student-management/classroom-summary/SelectFormInputClassroom.tsx
  frontend/src/components/teacher/student-management/view-students/AddClassroomOrStudentPopover.tsx
  frontend/src/components/teacher/student-management/view-students/EditStudentPopover.tsx
  frontend/src/components/teacher/student-management/view-students/StudentsTable.tsx
  frontend/src/components/teacher/view-sessions/TestSessionListItem.tsx
  frontend/src/constants/Routes.ts
  frontend/src/utils/ClassroomUtils.ts
Labels: ready to merge

#399 (0) feat: show individual question results
  frontend/src/components/admin/question-creation/question-elements/QuestionTextElement.tsx
  frontend/src/components/pages/teacher/DisplayAssessmentResultsPage/DisplayAssessmentResultsByStudentPage.tsx
  frontend/src/components/student/questions/Question.tsx
  frontend/src/components/student/questions/question-elements/QuestionText.tsx
  frontend/src/components/teacher/results/StudentAnswersSection/CorrectedQuestion.tsx
  frontend/src/components/teacher/results/StudentAnswersSection/QuestionList.tsx
  frontend/src/components/teacher/results/StudentAnswersSection/QuestionTitle.tsx
  frontend/src/components/teacher/results/StudentAnswersSection/index.tsx
  frontend/src/utils/GeneralUtils.ts
  frontend/src/utils/StudentUtils.ts
Labels: ready to merge

#427 (5) feat: fetch classroom drilldown data
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/types/classType.ts
  frontend/src/APIClients/queries/ClassQueries.ts
  frontend/src/APIClients/types/ClassClientTypes.ts
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomAssessmentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/DisplayClassroomStudentsPage.tsx
  frontend/src/components/pages/teacher/DisplayClassroomPage/index.tsx
  frontend/src/components/teacher/student-management/AddStudentModal.tsx
  frontend/src/utils/GeneralUtils.ts
Labels: ready to merge

#446 feat: Compute Top Performing Students
  backend/graphql/resolvers/testSessionResolvers.ts
  backend/graphql/types/testSessionType.ts
  backend/services/implementations/__tests__/testSessionService.test.ts
  backend/services/implementations/testSessionService.ts
  backend/services/interfaces/testSessionService.ts
  backend/testUtils/testSession.ts
  frontend/src/APIClients/queries/TestSessionQueries.ts
Labels: requested changes

#474 feat: short answer data vizualization
  frontend/src/components/admin/assessment-visualization/question-elements/ShortAnswerVisualizer.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/themes/components/progress.ts
  frontend/src/themes/index.ts
Labels: ready for review

#462 feat: add information page (distribute assessment - page 3)
  frontend/src/components/pages/teacher/DistributeAssessmentPage.tsx
  frontend/src/components/teacher/session-creation/DistributeAsessmentWrapper.tsx
  frontend/src/components/teacher/session-creation/steps/AddInformation.tsx
  frontend/src/components/teacher/student-management/classroom-summary/AddClassroomModal.tsx
  frontend/src/utils/GeneralUtils.ts
Labels: ready to merge

#475 feat: add multiple choice data visualization component
  frontend/src/components/admin/assessment-visualization/question-elements/MultipleChoiceVisualizer.tsx
  frontend/src/components/admin/assessment-visualization/question-elements/ShortAnswerVisualizer.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/themes/components/progress.ts
  frontend/src/themes/components/radio.ts
Labels: ready to merge

#477 feat: add multi select data visualization component
  frontend/src/components/admin/assessment-visualization/question-elements/MultiOptionVisualizerWrapper.tsx
  frontend/src/components/admin/assessment-visualization/question-elements/MultiSelectVisualizer.tsx
  frontend/src/components/admin/assessment-visualization/question-elements/MultipleChoiceVisualizer.tsx
  frontend/src/components/pages/ComponentLibrary.tsx
  frontend/src/themes/components/checkbox.ts
  frontend/src/themes/components/radio.ts
Labels: ready to merge

#476 feat: review page (distribute assessment - page 4)
  frontend/src/assets/icons.tsx
  frontend/src/components/admin/assessment-creation/QuestionCard.tsx
  frontend/src/components/admin/question-creation/QuestionElementItem.tsx
  frontend/src/components/admin/question-creation/question-elements/ImageElement.tsx
  frontend/src/components/admin/question-creation/question-elements/MultiOptionElement.tsx
  frontend/src/components/admin/question-creation/question-elements/ShortAnswerElement.tsx
  frontend/src/components/admin/question-creation/question-elements/modals/multi-option/MultiOption.tsx
  frontend/src/components/common/IconButton.tsx
  frontend/src/components/pages/teacher/DistributeAssessmentPage.tsx
  frontend/src/components/teacher/session-creation/AssessmentsTable.tsx
  frontend/src/components/teacher/session-creation/ReviewItem.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseAssessment.tsx
  frontend/src/components/teacher/session-creation/steps/ChooseClass.tsx
  frontend/src/components/teacher/session-creation/steps/Review.tsx
Labels: ready for review

#459 feat: delete classroom button on classroom cards
  backend/graphql/resolvers/classResolvers.ts
  backend/graphql/types/classType.ts
  frontend/src/APIClients/mutations/ClassMutations.ts
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomCard.tsx
  frontend/src/components/teacher/student-management/classroom-summary/ClassroomPopover.tsx
  frontend/src/components/teacher/student-management/classroom-summary/DeleteClassroomModal.tsx
Labels: ready to merge
